In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
import os

In [2]:
df = pd.read_csv('/Users/nischalpanthi/Group048_WI26/data/00-raw/crude-oil-price.csv')
df.head(5)

                        date  price  percentChange  change
0  1983-03-01 00:00:00+00:00  29.27            NaN     NaN
1  1983-04-01 00:00:00+00:00  30.63          4.646    1.36
2  1983-05-01 00:00:00+00:00  30.25         -1.241   -0.38
3  1983-06-01 00:00:00+00:00  31.38          3.736    1.13
4  1983-07-01 00:00:00+00:00  32.00          1.976    0.62

In [3]:
df.isnull().sum()
df_clean = df.dropna()
df_clean.isnull().sum()
df_clean.head(5)

                        date  price  percentChange  change
1  1983-04-01 00:00:00+00:00  30.63          4.646    1.36
2  1983-05-01 00:00:00+00:00  30.25         -1.241   -0.38
3  1983-06-01 00:00:00+00:00  31.38          3.736    1.13
4  1983-07-01 00:00:00+00:00  32.00          1.976    0.62
5  1983-08-01 00:00:00+00:00  31.59         -1.281   -0.41

In [4]:
df_clean = df.dropna().copy()
df_clean['date'] = pd.to_datetime(df_clean['date'])

In [5]:
num_duplicates = df_clean.duplicated(subset=['date']).sum()
#print("Duplicates after:", num_duplicates)
df_clean = df_clean.drop_duplicates(subset=['date']).reset_index(drop=True)

In [6]:
df_clean['price'] = pd.to_numeric(df_clean['price'], errors='coerce')
df_clean = df_clean.sort_values('date').reset_index(drop=True)

In [7]:
print("Shape:", df_clean.shape)
print("Date range:", df_clean['date'].min(), "to", df_clean['date'].max())
print("Date gaps (days):")
print(df_clean['date'].diff().dt.days.describe())

Shape: (515, 4)
Date range: 1983-04-01 00:00:00+00:00 to 2026-02-01 00:00:00+00:00
Date gaps (days):
count    514.000000
mean      30.441634
std        0.807795
min       28.000000
25%       30.000000
50%       31.000000
75%       31.000000
max       31.000000
Name: date, dtype: float64

In [8]:
#step 4 should be done

In [9]:
df_clean.head(5)

                       date  price  percentChange  change
0 1983-04-01 00:00:00+00:00  30.63          4.646    1.36
1 1983-05-01 00:00:00+00:00  30.25         -1.241   -0.38
2 1983-06-01 00:00:00+00:00  31.38          3.736    1.13
3 1983-07-01 00:00:00+00:00  32.00          1.976    0.62
4 1983-08-01 00:00:00+00:00  31.59         -1.281   -0.41

In [10]:
os.makedirs('data/01-clean', exist_ok=True)
df.to_csv('data/01-clean/oil-prices-clean.csv', index=False)